# Generated by Django 4.0.6 on 2022-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
