# Generated by Django 4.0.6 on 2022-11-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_room_options_rename_desc_room_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='desc',
        ),
    ]
